/* eslint-disable */ 
export const SET_VEGAN_SHOP_LOADING = "SET_VEGAN_SHOP_LOADING"
export const GET_VEGAN_SHOP_DETAILS = "GET_VEGAN_SHOP_DETAILS"
export const GET_VEGAN_SHOP_DETAIL_ID = "GET_VEGAN_SHOP_DETAIL_ID"
