/* eslint-disable */ 
export const SET_TOURS_TRAVEL_LOADING = "SET_TOURS_TRAVEL_LOADING"
export const GET_TOURS_TRAVEL_DETAILS = "GET_TOURS_TRAVEL_DETAILS"
export const GET_TOURS_TRAVEL_DETAIL_ID = "GET_TOURS_TRAVEL_DETAIL_ID"
