/* eslint-disable */ 
export const SET_MEDITATION_LOADING = "SET_MEDITATION_LOADING"
export const GET_ALL_MEDITATION_DETAILS = "GET_ALL_MEDITATION_DETAILS"
export const GET_BUDDIST_MEDITATION_DETAIL_ID = "GET_BUDDIST_MEDITATION_DETAIL_ID"
